name: Broken Link Checker

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Link Checker
        uses: lycheeverse/lychee-action@c053181aa0c3d17606addfe97a9075a32723548a # https://github.com/lycheeverse/lychee-action#security-tip
        with:
          args: --verbose --no-progress './**/*.md' './**/*.html' './**/*.js' './**/*.ts'
          fail: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
